accum-freq: 1
batch-size: 1
beta2: 0.95
data-key: "json"
dataset-resampled: True
delete-previous-checkpoint: False
epochs: 10
fsdp-amp: True
fsdp: True
grad-checkpointing: True
grad-clip-norm: 1
log-every-n-steps: 20
lr-cooldown-end: 3e-5
lr: 3e-3
model-norm: "gain_only_layer_norm"
model: "l65b_neox"
name: "65b_debug_2048_tri"
precision: "amp_bfloat16"
report-to: "wandb"
resume: "latest"
seed: 124
train-data-mix-weights: "0.725::0.275"
train-data: "openlm_mix_tri_s3"
train-num-samples: 4_100_000_000
wandb-project-name: "lm1"
warmup: 2000
wd: 0.1
workers: 4