accum-freq: 1
beta1: 0.9
beta2: 0.95
data-key: "json"
dataset-resampled: True
delete-previous-checkpoint: False
# Total 25B * 64 = 1.6T tokens
epochs: 64
fsdp: True
fsdp-limit-all-gathers: True
grad-checkpointing: True
grad-clip-norm: 1
log-every-n-steps: 20
model: "open_lm_7b"
name: "7b_lpln_fsdppure"
precision: "amp_bfloat16"
report-to: "wandb"
# resume: None
seed: 124
train-data-mix-weights: "0.725::0.275"
train-data: "openlm_mix_tri_s3"
train-num-samples: 25_000_000_000  # TODO
wandb-project-name: "lm1"
workers: 4

# Some important parameters, double checked with Mitchell:
batch-size: 16
ffn-type: swiglu
fsdp-amp: False
fsdp-pure-bf16: True
lr: 1e-3
lr-cooldown-end: 3e-5
model-norm: "lp_layer_norm"
qk-norm: True
warmup: 5000
wd: 0.1
z-loss-coefficient: 1e-4
