accum-freq: 1
batch-size: 8
beta1: 0.9
beta2: 0.95
data-key: "json"
dataset-resampled: True
delete-previous-checkpoint: False
# Total 10B * 70 = 700B tokens
epochs: 70
fsdp-amp: True
fsdp: True
fsdp-limit-all-gathers: True
grad-checkpointing: True
grad-clip-norm: 1
log-every-n-steps: 20
lr-cooldown-end: 3e-5
lr: 1e-3
model-norm: "gain_only_layer_norm"
model: "l7b_neox"
name: "7b_700b_2048_tri"
precision: "amp_bfloat16"
qk-norm: True
report-to: "wandb"
# resume: None
resume: "s3://tri-ml-sandbox-16011-us-east-1-datasets/sagemaker/achal.dave/openlm/achal-dave-openlm_2023-10-01-13-56-05-987/checkpoint/7b_700b_2048_tri/checkpoints/epoch_9.pt"
seed: 124
train-data-mix-weights: "0.725::0.275"
train-data: "openlm_mix_tri_s3"
train-num-samples: 10_000_000_000
wandb-project-name: "lm1"
warmup: 2000
wd: 0.1
workers: 4
z-loss-coefficient: 1e-4
